version: '3.8'
services:
  database:
    image: postgres:12.3-alpine
    container_name: database
    environment:
      - POSTGRES_PASSWORD=next_level
      - POSTGRES_USER=nlw
      - PGDATA=/data
    volumes:
      - "/tmp/pgdata:/data"
    ports:
      - "5432:5432"
  server:
    depends_on:
      - database
    build:
      context: ./
      dockerfile: ./.deploy/Dockerfile
    container_name: server
    environment:
      - DB_HOST=database
      - DB_PORT=5432
    ports:
      - "3000:80"
    
networks:
  nlw-network:
    driver: bridge
    name: nlw-network
